# Generated by Django 5.2.4 on 2025-08-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes_autos'),
        ),
    ]
